export const CREATE_EMPLOYEE ="CREATE_EMPLOYEE";
export  const LOAD_EMPLOYEE_SUCCESS="LOAD_EMPLOYEE_SUCCESS";
export const LOAD_STATES_SUCCESS = "LOAD_STATES_SUCCESS";
export const DELETE_EMPLOYEE_OPTIMISTIC="DELETE_EMPLOYEE_OPTIMISTIC";
export const CREATE_EMPLOYEE_SUCCESS="CREATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_SUCCESS="UPDATE_EMPLOYEE_SUCCESS";
